### ISSUE TITLE
Clicking on the heart of a memory card took me to the API

### ISSUE THREAD

**Issue by uskudarli** [enshkn/BOUN-SWE-573-SPRING-23#71]
I clicked on the lower left of card, assuming it was liking. I looks like a heard.

It took me to the API page: http://3.88.53.150/api/memories/9/

**Comment by uskudarli** [comment]
Likewise comments does the same.

**Comment by enshkn** [comment]
Hocam, In my routing settings, I founded that the API and view functions cause a conflict. I will make the necessary arrangement and inform you, Kind regards.

**Comment by enshkn** [comment]
the problem is in; base/templates/base/memory_component.html line 24.

{% url 'memory' memory.id %} should be changed to the following.
{% url 'memory-view' memory.id %}

The 'memory' redirect belongs to the API page.

**Comment by enshkn** [comment]
done and closed with the commit 3846619e064f7e92e55c4ac4f88a0aab4ddc2218
